### ISSUE TITLE
Error Reason: Deno.openKv is not a function.

### ISSUE THREAD

**Issue by blackglobeco** [ni554n/truecallerjs_bot#1]
Error Reason: Deno.openKv is not a function. What should I do?

<img width="370" alt="image" src="https://github.com/ni554n/truecallerjs_bot/assets/137195478/0e0ba334-d71e-4ea4-9cd8-42f8da42e5df">

**Comment by ni554n** [comment]
Deno KV is still in beta on Deno Deploy. Follow the README.md to request an access. I had to wait a week before they approved my request.
